# Generated by Django 4.1 on 2022-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog", name="bad_num", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog", name="good_num", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog", name="view_num", field=models.IntegerField(default=0),
        ),
    ]
